// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerificaDespesas.Context;

#nullable disable

namespace VerificaDespesas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250101152631_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VerificaDespesas.Models.Deputado", b =>
                {
                    b.Property<int>("DeputadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeputadoId"));

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Partido")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.HasKey("DeputadoId");

                    b.ToTable("Deputados");
                });

            modelBuilder.Entity("VerificaDespesas.Models.Despesa", b =>
                {
                    b.Property<int>("DespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DespesaId"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeputadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlDocumento")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("DespesaId");

                    b.HasIndex("DeputadoId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("VerificaDespesas.Models.Despesa", b =>
                {
                    b.HasOne("VerificaDespesas.Models.Deputado", "Deputado")
                        .WithMany("Despesas")
                        .HasForeignKey("DeputadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deputado");
                });

            modelBuilder.Entity("VerificaDespesas.Models.Deputado", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
